name: crypto_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip>=24.2
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.11.4
  - scikit-learn=1.3.2
  - pytz=2024.1
  - joblib=1.4.2
  - xgboost=1.7.6
  - streamlit=1.40.0
  - altair=5.3.0
  - python-dotenv=1.0.1
  - requests=2.32.3
  - tqdm=4.66.5
  - ccxt=4.3.59
  - beautifulsoup4=4.12.3
  - pip:
      - google-genai==0.5.2
      - google-news-api==0.0.6
      - torch==2.4.1
      - transformers==4.44.2
